/* NewsDay — исходные данные для наполнения БД (районы, категории, новости).
   Языки: uz (латиница), uzc (кириллица), ru, en */

export const DISTRICTS = [
  { id:"yunusabad",    uz:"Yunusobod",     uzc:"Юнусобод",     ru:"Юнусабадский",      en:"Yunusabad" },
  { id:"mirzo",        uz:"Mirzo Ulug'bek",uzc:"Мирзо Улуғбек",ru:"Мирзо-Улугбекский", en:"Mirzo Ulugbek" },
  { id:"chilanzar",    uz:"Chilonzor",     uzc:"Чилонзор",     ru:"Чиланзарский",      en:"Chilanzar" },
  { id:"yakkasaray",   uz:"Yakkasaroy",    uzc:"Яккасарой",    ru:"Яккасарайский",     en:"Yakkasaray" },
  { id:"shaykhantahur",uz:"Shayxontohur",  uzc:"Шайхонтоҳур",  ru:"Шайхантахурский",   en:"Shaykhantahur" },
  { id:"almazar",      uz:"Olmazor",       uzc:"Олмазор",      ru:"Алмазарский",       en:"Almazar" },
  { id:"bektemir",     uz:"Bektemir",      uzc:"Бектемир",     ru:"Бектемирский",      en:"Bektemir" },
  { id:"mirabad",      uz:"Mirobod",       uzc:"Миробод",      ru:"Мирабадский",       en:"Mirabad" },
  { id:"sergeli",      uz:"Sergeli",       uzc:"Сергели",      ru:"Сергелийский",      en:"Sergeli" },
  { id:"uchtepa",      uz:"Uchtepa",       uzc:"Учтепа",       ru:"Учтепинский",       en:"Uchtepa" },
  { id:"yashnabad",    uz:"Yashnobod",     uzc:"Яшнобод",      ru:"Яшнабадский",       en:"Yashnabad" },
];

export const CATEGORIES = [
  { id:"all",       color:"#ffffff", uz:"Hammasi",  uzc:"Ҳаммаси",  ru:"Все",          en:"All" },
  { id:"transport", color:"#3b82f6", uz:"Transport", uzc:"Транспорт",ru:"Транспорт",    en:"Transport" },
  { id:"utilities", color:"#f59e0b", uz:"Kommunal",  uzc:"Коммунал", ru:"ЖКХ",          en:"Utilities" },
  { id:"incident",  color:"#ef4444", uz:"Hodisalar", uzc:"Ҳодисалар",ru:"Происшествия", en:"Incidents" },
  { id:"events",    color:"#a855f7", uz:"Tadbirlar", uzc:"Тадбирлар",ru:"События",      en:"Events" },
  { id:"city",      color:"#22c55e", uz:"Shahar",    uzc:"Шаҳар",    ru:"Город",        en:"City" },
  { id:"business",  color:"#14b8a6", uz:"Iqtisod",   uzc:"Иқтисод",  ru:"Экономика",    en:"Business" },
];

export const NEWS = [
  { id:1, cat:"transport", district:"chilanzar", breaking:true, verified:true, time:18, source:"UzAvtoYo'l", status:"published",
    img:"https://images.unsplash.com/photo-1502877338535-766e1452684a?w=600&q=60",
    t:{ uz:"Chilonzorda metro yaqinida yo'l 3 kunga yopiladi", uzc:"Чилонзорда метро яқинида йўл 3 кунга ёпилади",
        ru:"На Чиланзаре перекроют дорогу у метро на 3 дня", en:"Road near Chilanzar metro closed for 3 days" },
    l:{ uz:"Ta'mirlash ishlari sababli harakat vaqtincha cheklanadi.", uzc:"Таъмирлаш ишлари сабабли ҳаракат вақтинча чекланади.",
        ru:"Из-за ремонтных работ движение временно ограничат.", en:"Traffic will be limited due to repair works." },
    b:{ uz:["Toshkent shahar hokimligi Chilonzor tumanida metro bekati yaqinidagi yo'lning 500 metrlik qismini yopish haqida ma'lum qildi.","Haydovchilarga muqobil yo'nalishlardan foydalanish tavsiya etiladi. Jamoat transporti vaqtincha o'zgartirilgan marshrut bo'ylab qatnaydi."],
        uzc:["Тошкент шаҳар ҳокимлиги Чилонзор туманида метро бекати яқинидаги йўлнинг 500 метрлик қисмини ёпиш ҳақида маълум қилди.","Ҳайдовчиларга муқобил йўналишлардан фойдаланиш тавсия этилади."],
        ru:["Хокимият Ташкента сообщил о закрытии 500-метрового участка дороги возле станции метро в Чиланзарском районе.","Водителям рекомендуют пользоваться объездными маршрутами. Общественный транспорт временно пойдёт по изменённому пути."],
        en:["Tashkent city administration announced the closure of a 500-meter stretch of road near a metro station in Chilanzar district.","Drivers are advised to use alternative routes. Public transport will temporarily follow a changed route."] } },

  { id:2, cat:"utilities", district:"yunusabad", breaking:false, verified:true, time:42, source:"Suvsoz", status:"published",
    img:"https://images.unsplash.com/photo-1585687501004-615dfc0f3f38?w=600&q=60",
    t:{ uz:"Yunusobodda ertaga suv o'chiriladi", uzc:"Юнусободда эртага сув ўчирилади",
        ru:"В Юнусабаде завтра отключат воду", en:"Water shutoff in Yunusabad tomorrow" },
    l:{ uz:"Profilaktika ishlari 09:00 dan 17:00 gacha davom etadi.", uzc:"Профилактика ишлари 09:00 дан 17:00 гача давом этади.",
        ru:"Профилактические работы продлятся с 09:00 до 17:00.", en:"Maintenance will run from 09:00 to 17:00." },
    b:{ uz:["\"Suvsoz\" korxonasi Yunusobod tumanining bir qator mahallalarida suv ta'minoti vaqtincha to'xtatilishini ma'lum qildi.","Aholidan suv zaxirasini oldindan g'amlab qo'yish so'raladi."],
        uzc:["«Сувсоз» корхонаси Юнусобод туманининг бир қатор маҳаллаларида сув таъминоти вақтинча тўхтатилишини маълум қилди.","Аҳолидан сув заҳирасини олдиндан ғамлаб қўйиш сўралади."],
        ru:["Предприятие «Сувсоз» сообщило о временном прекращении водоснабжения в ряде махаллей Юнусабадского района.","Жителей просят заранее запастись водой."],
        en:["The Suvsoz utility announced a temporary suspension of water supply in several mahallas of Yunusabad district.","Residents are asked to stock up on water in advance."] } },

  { id:3, cat:"events", district:"mirabad", breaking:false, verified:true, time:70, source:"Afisha.uz", status:"published",
    img:"https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=600&q=60",
    t:{ uz:"Shanba kuni Mirobodda ochiq havoda konsert", uzc:"Шанба куни Миробода очиқ ҳавода концерт",
        ru:"В субботу в Мирабаде концерт под открытым небом", en:"Open-air concert in Mirabad on Saturday" },
    l:{ uz:"Kirish bepul, boshlanishi soat 19:00 da.", uzc:"Кириш бепул, бошланиши соат 19:00 да.",
        ru:"Вход свободный, начало в 19:00.", en:"Free entry, starts at 19:00." },
    b:{ uz:["Mirobod tumani markaziy istirohat bog'ida mahalliy ijrochilar ishtirokidagi konsert bo'lib o'tadi.","Tashrifchilar uchun yozgi kafe va bolalar maydonchasi ishlaydi."],
        uzc:["Миробод туманининг марказий истироҳат боғида маҳаллий ижрочилар иштирокидаги концерт бўлиб ўтади.","Ташрифчилар учун ёзги кафе ва болалар майдончаси ишлайди."],
        ru:["В центральном парке Мирабадского района пройдёт концерт с участием местных исполнителей.","Для гостей будут работать летнее кафе и детская площадка."],
        en:["A concert featuring local performers will take place in the central park of Mirabad district.","A summer cafe and a children's playground will be open for visitors."] } },

  { id:4, cat:"incident", district:"sergeli", breaking:false, verified:false, time:95, source:"Community", status:"published",
    img:"https://images.unsplash.com/photo-1517649763962-0c623066013b?w=600&q=60",
    t:{ uz:"Sergelida yong'in: barcha aholi evakuatsiya qilindi", uzc:"Сергелида ёнғин: барча аҳоли эвакуация қилинди",
        ru:"В Сергели пожар: жильцов эвакуировали", en:"Fire in Sergeli: residents evacuated" },
    l:{ uz:"Jabrlanganlar yo'q, sabab aniqlanmoqda.", uzc:"Жабрланганлар йўқ, сабаб аниқланмоқда.",
        ru:"Пострадавших нет, причина устанавливается.", en:"No injuries, the cause is being investigated." },
    b:{ uz:["Sergeli tumanidagi ko'p qavatli uyda yong'in kelib chiqdi. Favqulodda vaziyatlar xodimlari olovni tez o'chirdi.","Ma'lumot jamoatchilik tomonidan yuborilgan va tekshirilmoqda."],
        uzc:["Сергели туманидаги кўп қаватли уйда ёнғин келиб чиқди. Фавқулодда вазиятлар ходимлари оловни тез ўчирди.","Маълумот жамоатчилик томонидан юборилган ва текширилмоқда."],
        ru:["В многоэтажном доме в Сергелийском районе произошёл пожар. Сотрудники МЧС быстро потушили огонь.","Информация прислана сообществом и проверяется."],
        en:["A fire broke out in an apartment building in Sergeli district. Emergency services quickly extinguished it.","The report was submitted by the community and is being verified."] } },

  { id:5, cat:"city", district:"yakkasaray", breaking:false, verified:true, time:130, source:"Toshkent hokimligi", status:"published",
    img:"https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=600&q=60",
    t:{ uz:"Yakkasaroyda yangi yashil xiyobon ochildi", uzc:"Яккасаройда янги яшил хиёбон очилди",
        ru:"В Яккасарае открыли новый зелёный бульвар", en:"New green boulevard opens in Yakkasaray" },
    l:{ uz:"1,2 km masofada 300 dan ortiq daraxt ekildi.", uzc:"1,2 км масофада 300 дан ортиқ дарахт экилди.",
        ru:"На 1,2 км высажено более 300 деревьев.", en:"Over 300 trees planted along 1.2 km." },
    b:{ uz:["Yakkasaroy tumanida piyodalar uchun yangi xiyobon foydalanishga topshirildi. Bu yerda velosiped yo'laklari va dam olish zonalari mavjud.","Loyiha shahar ko'kalamzorlashtirish dasturi doirasida amalga oshirildi."],
        uzc:["Яккасарой туманида пиёдалар учун янги хиёбон фойдаланишга топширилди. Бу ерда велосипед йўлаклари ва дам олиш зоналари мавжуд.","Лойиҳа шаҳар кўкаламзорлаштириш дастури доирасида амалга оширилди."],
        ru:["В Яккасарайском районе сдан новый пешеходный бульвар с велодорожками и зонами отдыха.","Проект реализован в рамках городской программы озеленения."],
        en:["A new pedestrian boulevard with bike lanes and rest areas has opened in Yakkasaray district.","The project was carried out as part of the city greening program."] } },

  { id:6, cat:"business", district:"mirzo", breaking:false, verified:true, time:180, source:"Spot.uz", status:"published",
    img:"https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&q=60",
    t:{ uz:"Mirzo Ulug'bekda yangi IT-park bloki quriladi", uzc:"Мирзо Улуғбекда янги IT-парк блоки қурилади",
        ru:"В Мирзо-Улугбекском районе построят новый блок IT-парка", en:"New IT Park block to be built in Mirzo Ulugbek" },
    l:{ uz:"Loyiha 2 mingdan ortiq ish o'rni yaratadi.", uzc:"Лойиҳа 2 мингдан ортиқ иш ўрни яратади.",
        ru:"Проект создаст более 2 тысяч рабочих мест.", en:"The project will create over 2,000 jobs." },
    b:{ uz:["Mirzo Ulug'bek tumanida IT-park uchun yangi ofis binosi qurilishi boshlandi. Bino zamonaviy startaplar va xalqaro kompaniyalarni qabul qiladi.","Qurilish kelgusi yil yakuniga qadar tugatilishi rejalashtirilgan."],
        uzc:["Мирзо Улуғбек туманида IT-парк учун янги офис биноси қурилиши бошланди. Бино замонавий стартаплар ва халқаро компанияларни қабул қилади.","Қурилиш келгуси йил якунига қадар тугатилиши режалаштирилган."],
        ru:["В Мирзо-Улугбекском районе началось строительство нового офисного здания IT-парка для стартапов и международных компаний.","Строительство планируют завершить к концу следующего года."],
        en:["Construction of a new IT Park office building for startups and international companies has begun in Mirzo Ulugbek district.","It is expected to be completed by the end of next year."] } },

  { id:7, cat:"transport", district:"almazar", breaking:false, verified:true, time:240, source:"Toshshahartransxizmat", status:"published",
    img:"https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&q=60",
    t:{ uz:"Olmazorda yangi avtobus marshruti ishga tushdi", uzc:"Олмазорда янги автобус маршрути ишга тушди",
        ru:"В Алмазаре запустили новый автобусный маршрут", en:"New bus route launched in Almazar" },
    l:{ uz:"№ 145 marshruti yangi turar-joy massivini bog'laydi.", uzc:"№ 145 маршрути янги турар-жой массивини боғлайди.",
        ru:"Маршрут № 145 свяжет новый жилой массив с центром.", en:"Route No. 145 connects a new residential area to the center." },
    b:{ uz:["Olmazor tumanida aholi so'roviga ko'ra yangi avtobus yo'nalishi ochildi. Avtobuslar har 12 daqiqada qatnaydi.","Marshrut ATTO to'lov tizimini qo'llab-quvvatlaydi."],
        uzc:["Олмазор туманида аҳоли сўровига кўра янги автобус йўналиши очилди. Автобуслар ҳар 12 дақиқада қатнайди.","Маршрут ATTO тўлов тизимини қўллаб-қувватлайди."],
        ru:["В Алмазарском районе по просьбам жителей открыли новый автобусный маршрут. Автобусы ходят каждые 12 минут.","Маршрут поддерживает оплату через систему ATTO."],
        en:["A new bus route has opened in Almazar district at residents' request. Buses run every 12 minutes.","The route supports ATTO payment."] } },

  { id:8, cat:"events", district:"shaykhantahur", breaking:false, verified:true, time:300, source:"Afisha.uz", status:"published",
    img:"https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=600&q=60",
    t:{ uz:"Chorsu bozorida hunarmandlar yarmarkasi", uzc:"Чорсу бозорида ҳунармандлар ярмаркаси",
        ru:"На Чорсу пройдёт ярмарка ремесленников", en:"Artisan fair at Chorsu bazaar" },
    l:{ uz:"Milliy hunarmandchilik namoyishi hafta oxirida.", uzc:"Миллий ҳунармандчилик намойиши ҳафта охирида.",
        ru:"Показ национальных ремёсел в эти выходные.", en:"National crafts showcase this weekend." },
    b:{ uz:["Shayxontohur tumanidagi Chorsu majmuasida an'anaviy hunarmandlar yarmarkasi tashkil etiladi. Ustalar kulolchilik va zardo'zlik namoyish etadi.","Tashrif buyuruvchilar mahsulotlarni sotib olishlari mumkin."],
        uzc:["Шайхонтоҳур туманидаги Чорсу мажмуасида анъанавий ҳунармандлар ярмаркаси ташкил этилади. Усталар кулолчилик ва зардўзлик намойиш этади.","Ташриф буюрувчилар маҳсулотларни сотиб олишлари мумкин."],
        ru:["В комплексе Чорсу в Шайхантахурском районе пройдёт традиционная ярмарка ремесленников. Мастера покажут гончарное дело и золотое шитьё.","Гости смогут приобрести изделия."],
        en:["A traditional artisan fair will be held at the Chorsu complex in Shaykhantahur district. Masters will showcase pottery and gold embroidery.","Visitors will be able to buy the goods."] } },

  { id:9, cat:"utilities", district:"uchtepa", breaking:false, verified:true, time:360, source:"Hududgaz", status:"published",
    img:"https://images.unsplash.com/photo-1607400201889-565b1ee75f8e?w=600&q=60",
    t:{ uz:"Uchtepada gaz bosimi vaqtincha pasayadi", uzc:"Учтепада газ босими вақтинча пасаяди",
        ru:"В Учтепе временно снизят давление газа", en:"Gas pressure temporarily reduced in Uchtepa" },
    l:{ uz:"Tarmoqni yangilash ishlari 2 kun davom etadi.", uzc:"Тармоқни янгилаш ишлари 2 кун давом этади.",
        ru:"Работы по обновлению сети продлятся 2 дня.", en:"Network upgrade works will last 2 days." },
    b:{ uz:["Uchtepa tumanida gaz ta'minoti tarmog'ini modernizatsiya qilish munosabati bilan bosim vaqtincha kamayadi.","Aholidan tushunish bilan qarash so'raladi."],
        uzc:["Учтепа туманида газ таъминоти тармоғини модернизация қилиш муносабати билан босим вақтинча камаяди.","Аҳолидан тушуниш билан қараш сўралади."],
        ru:["В Учтепинском районе в связи с модернизацией газовой сети временно снизится давление.","Жителей просят отнестись с пониманием."],
        en:["Due to modernization of the gas network in Uchtepa district, pressure will temporarily drop.","Residents are asked for their understanding."] } },

  { id:10, cat:"city", district:"yashnabad", breaking:false, verified:true, time:420, source:"Toshkent hokimligi", status:"published",
    img:"https://images.unsplash.com/photo-1573167243872-43c6433b9d40?w=600&q=60",
    t:{ uz:"Yashnobodda bolalar poliklinikasi ta'mirlandi", uzc:"Яшнободда болалар поликлиникаси таъмирланди",
        ru:"В Яшнабаде отремонтировали детскую поликлинику", en:"Children's clinic renovated in Yashnabad" },
    l:{ uz:"Yangi jihozlar o'rnatildi, qabul kengaytirildi.", uzc:"Янги жиҳозлар ўрнатилди, қабул кенгайтирилди.",
        ru:"Установлено новое оборудование, расширен приём.", en:"New equipment installed, capacity expanded." },
    b:{ uz:["Yashnobod tumanidagi bolalar poliklinikasida kapital ta'mir yakunlandi. Muassasa zamonaviy diagnostika jihozlari bilan ta'minlandi.","Kuniga qabul qilinadigan bemorlar soni oshdi."],
        uzc:["Яшнобод туманидаги болалар поликлиникасида капитал таъмир якунланди. Муассаса замонавий диагностика жиҳозлари билан таъминланди.","Кунига қабул қилинадиган беморлар сони ошди."],
        ru:["В детской поликлинике Яшнабадского района завершён капитальный ремонт. Учреждение оснастили современным диагностическим оборудованием.","Число принимаемых за день пациентов выросло."],
        en:["Major renovation has been completed at the children's clinic in Yashnabad district. It was equipped with modern diagnostics.","The number of patients seen per day has increased."] } },

  { id:11, cat:"incident", district:"bektemir", breaking:false, verified:true, time:500, source:"IIV", status:"published",
    img:"https://images.unsplash.com/photo-1449157291145-7efd050a4d0e?w=600&q=60",
    t:{ uz:"Bektemirda ko'prik ta'mir tufayli qisman yopiq", uzc:"Бектемирда кўприк таъмир туфайли қисман ёпиқ",
        ru:"В Бектемире мост частично закрыт на ремонт", en:"Bridge partly closed for repair in Bektemir" },
    l:{ uz:"Bir tasma harakat uchun ochiq qoladi.", uzc:"Бир тасма ҳаракат учун очиқ қолади.",
        ru:"Одна полоса остаётся открытой для движения.", en:"One lane remains open for traffic." },
    b:{ uz:["Bektemir tumanidagi avtomobil ko'prigida ta'mirlash boshlandi. Xavfsizlik yuzasidan harakat bir tasmaga cheklandi.","Ishlar bir hafta ichida yakunlanishi kutilmoqda."],
        uzc:["Бектемир туманидаги автомобиль кўпригида таъмирлаш бошланди. Хавфсизлик юзасидан ҳаракат бир тасмага чекланди.","Ишлар бир ҳафта ичида якунланиши кутилмоқда."],
        ru:["На автомобильном мосту в Бектемирском районе начался ремонт. В целях безопасности движение ограничили одной полосой.","Работы планируют завершить в течение недели."],
        en:["Repairs have begun on a road bridge in Bektemir district. For safety, traffic was limited to one lane.","Works are expected to finish within a week."] } },

  { id:12, cat:"business", district:"chilanzar", breaking:false, verified:true, time:600, source:"Kun.uz", status:"published",
    img:"https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&q=60",
    t:{ uz:"Chilonzorda yangi savdo markazi ochildi", uzc:"Чилонзорда янги савдо маркази очилди",
        ru:"На Чиланзаре открылся новый торговый центр", en:"New shopping mall opens in Chilanzar" },
    l:{ uz:"120 dan ortiq do'kon va oziq-ovqat maydoni.", uzc:"120 дан ортиқ дўкон ва озиқ-овқат майдони.",
        ru:"Более 120 магазинов и фуд-корт.", en:"Over 120 stores and a food court." },
    b:{ uz:["Chilonzor tumanida yirik savdo-ko'ngilochar markaz ochildi. Bu yerda kinoteatr, do'konlar va bolalar zonasi joylashgan.","Markaz yuzlab yangi ish o'rinlarini yaratdi."],
        uzc:["Чилонзор туманида йирик савдо-кўнгилочар марказ очилди. Бу ерда кинотеатр, дўконлар ва болалар зонаси жойлашган.","Марказ юзлаб янги иш ўринларини яратди."],
        ru:["В Чиланзарском районе открылся крупный торгово-развлекательный центр с кинотеатром, магазинами и детской зоной.","Центр создал сотни новых рабочих мест."],
        en:["A large shopping and entertainment center with a cinema, stores and a kids' zone has opened in Chilanzar district.","It created hundreds of new jobs."] } },
];
